### ISSUE TITLE
끄적끄적

### ISSUE THREAD

**Issue by Ojongseok** [Ojongseok/Android_SketchBook#1]
## Description
Android 이것저것 연습하는 레포

## To-Do
- [x] Jetpack Navigation 세팅
- [ ] 스켈레톤 UI 적용
- [ ] DataBinding 적용
- [ ] DataBinding에 BindingAdapter 적용
